### PR TITLE
Styles file have been changed

### PR DESCRIPTION
**Pull request by Rishav1707**
I have made some changes in the Styles.css file.
Changed the Button UI and border of Input elements. 
If you find this helpful pls merge this request...

### CODE REVIEW

**Comment by Rishav1707** [comment]
Anyone is there?? For reviews.

@Harshchourasiya @vrindavan @SrijanDas @JPatil22

**Review by vrindavan — CHANGES_REQUESTED** [review]
I think the colors are fine but you can make sure that the color changes exactly like the hover animation. The button pops out quicker than the color which looks a bit weird if you ask me.

**Comment by Rishav1707** [comment]
> I think the colors are fine but you can make sure that the color changes exactly like the hover animation. The button pops out quicker than the color which looks a bit weird if you ask me.

Ok I will change it

**Comment by Rishav1707** [comment]
Thank you for your patience😊

**Pull request closed without merging**
