### PR TITLE
Download button

### PR DESCRIPTION
**Pull request by SumitKanth**
Created a download button for downloading the current meme created by user

### CODE REVIEW

**Review by Pritam0077 — APPROVED** [review]
I have made all the required changes

**Comment by SumitKanth** [comment]
You have merged all changes ?

**Comment by Pritam0077** [comment]
Yes

**Comment by SumitKanth** [comment]
not showing in website 👀

**Comment by SumitKanth** [comment]
ooh, not seen that.... ok

**Pull request merged**
